//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public int Id { get; set; }
        public int ApplicantId { get; set; }
        public int EmployeeId { get; set; }
        public int VacancyId { get; set; }
        public System.DateTime AttachedDate { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual InterviewStatu InterviewStatu { get; set; }
        public virtual Vacancy Vacancy { get; set; }
    }
}
